GET http://localhost:8081/crud-spring/api/v1/genero HTTP/1.1
content-type: application/json

###
GET http://localhost:8081/crud-spring/api/v1/genero/22 HTTP/1.1
content-type: application/json

###
GET http://localhost:8081/crud-spring/api/v1/estado HTTP/1.1
content-type: application/json

###
GET http://localhost:8081/crud-spring/api/v1/estado/22 HTTP/1.1
content-type: application/json

###
GET http://localhost:8081/crud-spring/api/v1/estado/nome?param=Bahia HTTP/1.1
content-type: application/json

###
GET http://localhost:8081/crud-spring/api/v1/estado/sigla?param=DF HTTP/1.1
content-type: application/json

